musicArray = []
musicArrayCover = []
musicArray_name = []
musicArray_artist = []
addMusic('逃!','逃!','逃!', '乐正绫（AI）,VO大自然,OQQ')
addMusic('信仰与存在','信仰与存在','信仰と存在 ', '他人事,feat.否')
addMusic('UntitledWorld','UntitledWorld','Untitled World', 'ReoNa,草野华余子，毛蟹（LIVE LAB.），堀江晶太')
addMusic('狼之主','狼之主', '狼之主-叙拉古OST', 'Adam Gubman,Shawn W. Smith')
addMusic('殉道之人','殉道之人','殉道之人', 'Erik Castro')
addMusic('AmatsukaUto-KING','AmatsukaUto-KING','KING', 'Amatsuka Uto')
addMusic('HoshikawaSara-Vampire(Melophobia)','HoshikawaSara-Vampire(Melophobia)','Vampire', 'Hoshikawa Sara')
addMusic('InuiToko-phony(-InuiToko-)','InuiToko-phony(-InuiToko-)','phony', 'Inui Toko')
addMusic('キャットラビング-full-巡音ルカ+宵崎奏+東雲 絵名','CatLoving-or','キャットラビング','巡音ルカ 宵崎奏 東雲絵名')
addMusic('CatLoving猫咪爱抚-甘城','CatLoving','キャットラビング', 'Nachoneko(甘城なつき)')
addMusic('七柠ECHO','七柠ECHO', 'ECHO', '七柠')
addMusic('茶理理Echo','茶理理Echo', 'ECHO', '茶理理,feat.人形兎')
// addMusic('威风堂堂-hanser美式娇喘','','威风堂堂-美式娇喘', 'hanser')
addMusic('威风堂堂茶理理','威风堂堂茶理理','威风堂堂', '茶理理')
addMusic('[Giga]BeyondTheWay','BeyondTheWay','Beyond the way', 'Giga,初音ミク,鏡音リン,鏡音レン')
addMusic('弱酸性-BeyondTheWay','BeyondTheWay','Beyond the way','弱酸性')
addMusic('像神一样呐-Ado','','像神一样呐', 'Ado')
addMusic('像神一样呐-25时','像神一样呐-25时','像神一样呐', '25时')
addMusic('命に嫌われている。（セカイver.）vol.宵崎奏×初音ミク','命嫌','命に嫌われている（セカイver.）', 'vol.宵崎奏×初音ミク')
addMusic('调音什么的还是算了吧[辞めてやるよ歌い手なんか ]','','调音什么的还是算了吧', 'SV. 重音テト')
addMusic('室内系的TrackMaker','室内系的TrackMaker','インドア系ならトラックメイカー', 'Yunomi')
// addMusic('Testify-void(Mournfinale)feat.星熊南巫','Testify','Testify - void (Mournfinale)', 'feat. 星熊南巫')
addMusic('Tempestissimo-t+pazolite','Tempestissimo-t+pazolite','Tempestissimo', 't+pazolite')
addMusic('MVURBD','MVURBD','MVURBD', '	ETIA.')
addMusic('USAO-Cyaegha','USAO-Cyaegha','Cyaegha', 'USAO')
// addMusic('666','666', '666', 'RoughSketch')
// addMusic('守望先锋-中国话','','守望先锋-中国话', '')
// addMusic('HideandSeek','','Hide and Seek', '')
addMusic('无职转生Ⅱ特殊ED：七星静香「ツバサ」','无职转生Ⅱ特殊ED：七星「ツバサ」','ツバサ', '无职转生Ⅱ-七星')
addMusic('不可思議のカルテ 双葉理央 Ver.','不可思議のカルテ','不可思議のカルテ', '双葉理央 Ver.')
addMusic('当年菜鸟-云翼星辰','','当年菜鸟', '云翼星辰')
addMusic('主题曲《饿殍 明末千里行》','','饿殍 明末千里行', 'haner,零创游戏')
addMusic('冰雪中的花','雪之本境','冰雪中的花','SPtime-《雪之本境》')
// addMusic('雑踏、僕らの街-熙熙攘攘，我们的城市','雑踏、僕らの街-熙熙攘攘，我们的城市','雑踏、僕らの街','井芹仁菜,河原木桃香,安和昴,海老冢智')
addMusic('未来的志愿书（重制版）-西国之海妖','高恋','未来的志愿书(重制版)','西国之海妖')
addMusic('未来的志愿书——高考恋爱一百天主题曲','高恋','未来的志愿书','高考恋爱一百天主题曲')
addMusic('枫海-真恋寄语枫秋','枫海','枫海','真恋寄语枫秋')
addMusic('月海之音-真恋寄语枫秋','枫海','月海之音','真恋寄语枫秋')
addMusic('永恒的等待（完整版）-真恋寄语枫秋','枫海','永恒的等待(完整版)','真恋寄语枫秋')
addMusic('幽灵唯我一人','','幽灵唯我一人', '广井菊里')
addMusic('','','','')

addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')
addMusic('','','','')


console.log(musicArray)
console.log(musicArrayCover)
console.log(musicArray_name)
console.log(musicArray_artist)